---
title: "Limits Information"
output: html_document
---

## Introduction

The `limits.csv` file in the `data-raw` directory 
is a spreadsheet of the information about the upper and lower limits for
a variety of variables. It is used by the `calc_limits()` function 
to assign limits to user's data. The `limits.csv`
file should be opened and edited using a spreadsheet editor 
such as Excel or LibreOffice and resaved as `limits.csv`.
Additional information on the units and codes for particular variables
is stored in the `codes.csv` table in the `data-raw` directory.

## Reference Document

**The `limits.csv` file  contains the limits defined in the 
reference documents `data-raw/BC_2006.pdf` (*British Columbia Approved Water Quality Guidelines 2006 Edition*). Where values were not available in this document they were provided (and or clarified) by MoE water staff.
Although other limits
are defined on the web the formats are inconsistent and 
the stability of the links uncertain.
Consequently, it was decided to define the limits with regard to a clearly-defined
and dated reference document and associated email. 
If a similar document was produced in the future
then the `limits.csv` file could be updated to contain the information
from both documents. The `calc_limits()` function could then be modified to allow 
users to define which reference document
they wanted to use.

## Freshwater Life

The `limits.csv` file contains the limits for Freshwater Life (Aquatic Life) 
for 
water samples taken from the water column in British Columbia. 
Although limits are defined for 
other uses the complexity of subcategories and lack of consistent terms
prevented digitization of the information. For example, the following
terms described subcategories of Drinking Water: Supply, Raw, chemically assisted filtration,
slow sand or diatomaceous earth filtration, membrane filtration, raw untreated,
- lakes, - no treatment, - disinfection only, - partial treatment, - complete treatment,
- includes food processing water
- aesthetics (taste and odour), - toxicity, (without treatment for
colour removal), - with chlorination, - other disinfection and Source.

Variables that are not based on water samples taken from the water column
such as chlorophyll-a concentrations 
for periphytic algae or interstitial dissolved oxygen levels are not included
in the `limits.csv` file. 

Finally, the limits for Turbidity, Sediment,
Total Ammonia Nitrogen, Polycyclic Aromatic Hydrocarbons (PAHs), 
Chlorophenols, pH, Total Gas Pressure (TGP), Color, Organic Carbon and
Temperature are excluded due to their complexity, lack or clarity
and/or dependence on background levels.

## Data

The `limits.csv` file contains the following columns: 

- Variable - The name of the parameter of interest, i.e., Total Phosphate, Arsenic, Nitrogen etc.
- Average - Whether or not the limits are the maximum value (default leave cell blank) 
or the mean or geomean or median from at least 5 weekly samples taken in a period of 30 days.
- Condition	- Any conditions on the levels as a valid logical R expression.
- UpperLimit - The maximum level as a valid R expression where other variables are referenced
by their code.
- Units - The units for the lower and upper limits where the permitted values are
ng/L, ug/L, mg/L, pH and /dL (in the case of the `codes.csv` table).
- Table - The table in the reference document.
- Reference - The reference document where the only permitted values are BC_2006, MOE_PERS_COMM_2014, and MOE_PERS_COMM_2015.
- Use - The use where currently the only permitted value is Freshwater Use.

The `codes.csv` file contains 3 columns. The Variable,  and Units columns
contain the same information as the `limits.csv` table. The Code column
contains the code for the Variable which is used in the definitions
of some of the Conditions and Lower and Upper Limits in the `limits.csv` table.
The code column is also useful for plotting purposes.
